# -*- coding: utf-8 -*-
"""ml yt vid9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YouC1nY4X4r2mEx8bKGsZpYFaVdwKszp
"""

import pandas as pd
import numpy as np

from google.colab import files
files.upload()

df=pd.read_csv('salaries.csv')
df.head()

input=df.drop('salary_more_then_100k',axis=1)

output=df.salary_more_then_100k

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

input['company_lb']=lb.fit_transform(input[['company']])
input.head()

input.company_lb.unique()

np.unique(input[['company']])

input['job_lb']=lb.fit_transform(input[['job']])
input['degree_lb']=lb.fit_transform(input[['degree']])
input.head()



for i in input.columns:
  print(i, np.unique(input[[i]]),sep='\n')

new_input=input[['company_lb','job_lb','degree_lb']]

from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()

tree.fit(new_input,output)

tree.score(new_input,output)

tree.predict([[2,2,1]])

dict1=dict(zip(lb.classes_,lb.transform(lb.classes_)))
dict1

tree2=DecisionTreeClassifier(criterion='entropy')

tree2.fit(new_input,output)

tree2.score(new_input,output)

files.upload()

df=pd.read_csv('titanic.csv')
len(df)

df.head()

df.drop_duplicates(inplace=True)

len(df)

df.isna().sum()

df.Embarked.unique()

df['Age'].isna().sum()/len(df)

df[df.Age.isna()]

df.Age.median()

df.Age.mean()

import seaborn as sns

sns.distplot(df.Age)

df2=df

df2['Age']=df2['Age'].fillna(df2.Age.median())
# hoteldata['agent']=hoteldata['agent'].fillna(hoteldata['agent'].mode()[0])

sns.distplot(df.Age)

df2.isna().sum()

df.Age.fillna(df.Age.mean(),inplace=True)

df.isna().sum()

df.columns

final=df[['Survived', 'Pclass', 'Sex', 'Age', 'Fare']]

final.head()

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()

final['sex_lb']=lb.fit_transform(final[['Sex']])
final.head()

d=dict(zip(lb.classes_,lb.transform(lb.classes_)))
d

x=final.drop(['Survived','Sex'],axis=1)
y=df['Survived']
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)



from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()

tree.fit(xtrain,ytrain)

tree.score(xtest,ytest)

# trying with age filled with median
df2=pd.read_csv('titanic.csv')

df2.Age.fillna(df2.Age.median(),inplace=True)
df2.isna().sum()

df2['sexlb']=lb.fit_transform(df2[['Sex']])
df2.head()

x=df2[['Pclass','sexlb','Age','Fare']]
y=df2['Survived']

xt,xd,yt,yd=train_test_split(x,y,test_size=0.3,random_state=0)

tree2=DecisionTreeClassifier()

tree2.fit(xt,yt)

tree2.score(xd,yd)

tree3=DecisionTreeClassifier(criterion='entropy')

tree3.fit(xt,yt)

tree3.score(xd,yd)

